### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by dirtymike0330** [Bango1999/S3#10]
I assume I have done something incorrectly, but I believe I got the S3 and SLSC stuff running correctly. However, something is lost during the export to the S3 server. On the website, it does not display all of the Slmodstats information. Specifically, only the following planes: A10, F15, F5, F86, P51, M2k, Spit, BF109 are showing on the table despite us flying Hornets, F14s, etc. Also doesn't seem to accurately reflect flight hours, kills, etc. User names ARE populating, so I think I am close.

**Comment by Bango1999** [comment]
Hi @rainman369, I'm glad you're interested in using my tool!

I haven't updated this project in 4 years. So any new modules that have been released since then, will not show up in the list, including the Hornet, F14, etc.

This repo slowly got deprecated and overshadowed by a project I hosted on my DCS github. That project is called SLbot, and it attempts to combine S3, SLSC, and a discord bot so you can type commands in your discord to get particular stats for players, servers, stat types.  https://github.com/flying-huckleberry/SLbot

Getting back on track and addressing your issues, If you'd like I can send out a quick update when I get home to add the new modules to the web view.  I don't have anything set up to test this, however, so I would want to push that update to develop branch and let you use that.

Can you provide an example of the flight hours in SLmod Stats vs what's displayed in S3, and/or explain why you think its not accurate?  There's a certain formula I used to convert Slmod time to floating-point hours, and I don't know why that would have changed. 

`(Math.round((100*val/3600))/100)` - 3600 seconds in 1 hour, and the 100 used for floating point significant digit buffering.

**Comment by Bango1999** [comment]
Same question for kills, etc. Anything that doesn't make sense to you, can you provide and example and/or explain further why you think its inaccurate?

**Comment by dirtymike0330** [comment]
Thanks for the fast response! 

I think the kills/flying hours is actually answered by your response ref the modules :D 
For your reference, here is my current slmodstats and the corresponding output on the website: https://drive.google.com/drive/folders/1fL_KAePdB5X0Zt4mz8A7Fn_b_Byqswuo?usp=sharing

As far as you updating it on my account- Firstly, I appreciate the offer! I really want to get something operational for my squad! But would it save you the trouble if I just look into the SLBOT side of things? Whatever is convenient for you would work for me and, again, I appreciate the reply.

**Comment by Bango1999** [comment]
@rainman369 It appears you pretty much have this working already, so I'm happy to add the new aircraft for you.

If you're particularly interested in the discord bot feature that would be a better reason to transition into SLbot, however I can tell you there are a few enhancements to this basic web view within SLbot that haven't been retroactively added to S3. It also has a nicer UI and logging mechanism which you can see from the screenshot in that readme.

Additionally, SLbot is unfinished. SLSC is still an independent program, and there are quite a few tasks and features that I can't guarantee at this point will ever be finished. https://trello.com/b/qzJFKqSt/slbot.

**Comment by dirtymike0330** [comment]
I really appreciate it! And I will take a deeper look into SLbot and make a decision after I get this one sorted it out. Great work all around btw! Thanks again!

**Comment by Bango1999** [comment]
Pull Request is up `develop` -> `master` https://github.com/Bango1999/S3/pull/11

Please give the #11 a glance @rainman369 and see if [develop](https://github.com/Bango1999/S3/tree/develop) suits your fancy.
Also would be rad if you want to give it a proverbial test and approval, but not necessary.

If you want more A/C added in the future, I'll need to know their string designations in the `SLmodStats.lua` table.

**Comment by Bango1999** [comment]
Fixed by #11
