### ISSUE TITLE
Feature request: Total hours

### ISSUE THREAD

**Issue by mvee** [Bango1999/S3#5]
Hi, could you add total hours statistics for players?

**Comment by Bango1999** [comment]
1. the sum of the other columns in the Hours table (whitelisted airframe hours)?
2. or alternatively, a sum of a player's hours in *all* airframes?

Sounds doable, I am leaning toward number 1 to keep it relevant and comparable.

**Comment by mvee** [comment]
Maybe both, the second being "Total time on server" or similar?

**Comment by Bango1999** [comment]
I'm moving forward with number 1. If you look at the experimental JSON view, you can see what raw data we have to work with.  Total time on server is not really a statistic that can be generated, due to time not being logged in spectator view or in the role selection screen.

Sometime in the future, I would like to implement mission-specific stats, and then S3 can be like a big archive of single-mission datasets.  But that is not something I've got planned for the immediate future. 

For now, I will see about implementing number 1 as written above, and not number 2, for these reasons:

1. The logic that converts the JSON into table-format is fairly convoluted as-is, (even after total refactoring)
2. I'm worried about width issues on the table columns. If there are too many whitelisted aircraft, data will be scrunched and/or overflow its X-bounds anyway.  If we add 2 more columns, this limitation only exacerbates itself.  I feel that 1/2 is a good compromise.
